
SUCCEED='SUCCEED'
FAILED='FAILED'

FORCE_RESIZE_IMAGE=True


DEFAULT_AVAILABLE_PRODUCT_FOR_SHOP=60
DEFAULT_SHIPPING_FEE=2000
CURRENCY=' تومان'


# Image Size for models
PRODUCT_IMAGE_WIDTH=600
PRODUCT_IMAGE_HEIGHT=600
PRODUCT_THUMBNAIL_WIDTH=250
PRODUCT_THUMBNAIL_HEIGHT=250
CATEGORY_IMAGE_WIDTH=250
CATEGORY_IMAGE_HEIGHT=250
PROFILE_IMAGE_WIDTH=150
PROFILE_IMAGE_HEIGHT=150

SUPPLIER_IMAGE_WIDTH=500
SUPPLIER_IMAGE_HEIGHT=350

SHIPPER_IMAGE_WIDTH=500
SHIPPER_IMAGE_HEIGHT=350


DEFAULT_ORDER_LIST_FOR_USER=20
DEFAULT_ORDER_LIST_FOR_SUPPLIER=200
DEFAULT_ORDER_LIST_FOR_SHIPPER=20



CAN_EDIT_MOBILE=False
CAN_EDIT_EMAIL=False

ACTION_LIKE='LIKE'
ACTION_DISLIKE='DISLIKE'


NOTIFICATION_UNSEEN_COUNT=10
NOTIFICATION_SEEN_COUNT=10
NOTIFICATION_ALL_COUNT=20