# Generated by Django 3.1 on 2020-08-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200814_1640'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.region', verbose_name='region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.region', verbose_name='region'),
            preserve_default=False,
        ),
    ]
