# Generated by Django 3.1 on 2020-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200815_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='agent',
        ),
        migrations.AddField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
    ]
