# Generated by Django 3.1 on 2020-08-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200816_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipper',
            old_name='big_image',
            new_name='image_origin',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='big_image',
            new_name='image_origin',
        ),
    ]
