# Generated by Django 3.1 on 2020-08-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200816_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_origin',
        ),
    ]
