# Generated by Django 3.1 on 2020-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200816_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Category/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Product/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Product/thumbnail/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Supplier/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Supplier/', verbose_name='تصویر'),
        ),
    ]
