# Generated by Django 3.1 on 2020-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200814_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شده'),
        ),
    ]
