# Generated by Django 3.1 on 2020-08-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200814_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('priority', models.IntegerField(verbose_name='priority')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'ResumeCategorys',
            },
        ),
        migrations.AlterField(
            model_name='metadata',
            name='key',
            field=models.CharField(default='name', max_length=50, verbose_name='key name'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.CharField(max_length=50, verbose_name='key value'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='subtitle')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.resumecategory', verbose_name='category')),
                ('documents', models.ManyToManyField(to='dashboard.Document', verbose_name='documents')),
                ('links', models.ManyToManyField(to='dashboard.Link', verbose_name='links')),
                ('profie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
