# Generated by Django 3.1 on 2020-08-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200818_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='social_links',
            field=models.ManyToManyField(to='dashboard.SocialLink', verbose_name='social_links'),
        ),
    ]
