# Generated by Django 3.1 on 2020-08-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ourteam_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.resume', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='social_links',
            field=models.ManyToManyField(blank=True, to='dashboard.SocialLink', verbose_name='social_links'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='documents',
            field=models.ManyToManyField(blank=True, to='dashboard.Document', verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='links',
            field=models.ManyToManyField(blank=True, to='dashboard.Link', verbose_name='links'),
        ),
    ]
