# Generated by Django 3.1 on 2020-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200818_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecategory',
            name='title',
            field=models.CharField(choices=[('تجربه ها', 'تجربه ها'), ('آموزش ها', 'آموزش ها'), ('مهارت ها', 'مهارت ها'), ('علاقه ها', 'علاقه ها'), ('گواهینامه ها', 'گواهینامه ها'), ('جایزه ها', 'جایزه ها')], default='آموزش ها', max_length=50, verbose_name='title'),
        ),
    ]
