# Generated by Django 3.1 on 2020-08-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200818_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profie',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='resume_categories',
            field=models.ManyToManyField(to='dashboard.ResumeCategory', verbose_name='ResumeCategories'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile', verbose_name='profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='resumes',
            field=models.ManyToManyField(to='dashboard.Resume', verbose_name='resume'),
        ),
    ]
