# Generated by Django 3.1 on 2020-08-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200818_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecategory',
            name='profile',
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='our_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ourteam', verbose_name='our_team'),
            preserve_default=False,
        ),
    ]
