# Generated by Django 3.1 on 2020-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200819_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='row_number',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='icon',
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(default=10000, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurService/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='links',
            field=models.ManyToManyField(to='dashboard.Link', verbose_name='links'),
        ),
    ]
