# Generated by Django 3.1 on 2020-08-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0014_auto_20200819_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('موبایل', 'موبایل'), ('تلفن', 'تلفن'), ('ایمیل', 'ایمیل'), ('آدرس', 'آدرس'), ('یادداشت', 'یادداشت')], default='موبایل', max_length=50, verbose_name='entry_type')),
                ('entry_value', models.CharField(max_length=50, verbose_name='value')),
            ],
            options={
                'verbose_name': 'EntryDetail',
                'verbose_name_plural': 'EntryDetails',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='company')),
                ('details', models.ManyToManyField(blank=True, to='phonebook.EntryDetail', verbose_name='details')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entrys',
            },
        ),
    ]
