# Generated by Django 3.1 on 2020-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydetail',
            name='entry_type',
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='entry_name',
            field=models.CharField(choices=[('موبایل', 'موبایل'), ('تلفن', 'تلفن'), ('ایمیل', 'ایمیل'), ('آدرس', 'آدرس'), ('یادداشت', 'یادداشت')], default='موبایل', max_length=50, verbose_name='entry_name'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='entry_value',
            field=models.CharField(max_length=50, verbose_name='entry_value'),
        ),
    ]
