# Generated by Django 3.1 on 2020-08-21 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20200822_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestservice',
            options={'verbose_name': 'RequestService', 'verbose_name_plural': 'RequestServices'},
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='date_needed',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 21, 12, 4, 447372, tzinfo=utc), verbose_name='date_needed'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='vehicle_type',
            field=models.CharField(choices=[('وانت', 'وانت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='تاکسی', max_length=50, verbose_name='نوع وسیله '),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('وانت', 'وانت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='تاکسی', max_length=50, verbose_name='نوع وسیله '),
        ),
    ]
