# Generated by Django 3.1 on 2020-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200815_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('جدید', 'جدید'), ('آماده واگذاری', 'آماده واگذاری'), ('در حال انجام', 'در حال انجام'), ('آماده بررسی', 'آماده بررسی'), ('در حال بررسی', 'در حال بررسی'), ('تایید شده', 'تایید شده'), ('انجام شده', 'انجام شده'), ('تحویل شده', 'تحویل شده')], default='جدید', max_length=50, verbose_name='status'),
        ),
    ]
